FROM node:20-slim

RUN apt-get update && apt-get install -y openssl

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 4000

# Elsőként szinkronizálja a sémát a Supabase-szel (adatvesztés nélkül), majd elindítja a szervert
CMD ["sh", "-c", "npx prisma db push && node index.js"]
