import NavBar from "@/src/components/navbar";
import { AuthProvider } from "@/src/context/AuthContext";
import { Toaster } from "sonner";
import type { Metadata } from "next";
import "./global.css";
import { CartProvider } from "@/src/context/CartContext";
export const metadata: Metadata = {
  title: "LoopMarket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu" suppressHydrationWarning>
      <body className="bg-slate-950 min-h-screen">
        <AuthProvider>
          <CartProvider>
            <NavBar />
            {/* A pt-20 (5rem/80px) pontosan a NavBar magassága */}
            <main className="pt-20">{children}</main>
            <Toaster position="top-left" theme="dark" richColors />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
