export const PERMS = {
  PROFILE_UPDATE: "PROFILE_UPDATE",
  PROFILE_DEACTIVATE: "PROFILE_DEACTIVATE",
  PROFILE_ACTIVATE: "PROFILE_ACTIVATE",
  CART_MANAGE: "CART_MANAGE",

  PRODUCTS_FULL_ACCESS: "PRODUCTS_FULL_ACCESS",
  CATEGORIES_MANAGE: "CATEGORIES_MANAGE",
  ATTRIBUTES_MANAGE: "ATTRIBUTES_MANAGE",
  VENDORS_MANAGE: "VENDORS_MANAGE",

  ORDERS_VIEW: "ORDERS_VIEW",
  ORDERS_MANAGE: "ORDERS_MANAGE",
  ORDER_STATUS_MANAGE: "ORDER_STATUS_MANAGE",
  PAYMENT_METHODS_MANAGE: "PAYMENT_METHODS_MANAGE",

  TICKET_VIEW: "TICKET_VIEW",
  TICKET_REPLY: "TICKET_REPLY",
  TICKET_DELETE: "TICKET_DELETE",
  TICKET_STATUS_MANAGE: "TICKET_STATUS_MANAGE",

  USER_MANAGEMENT: "USER_MANAGEMENT",
  EMAIL_LOGS_VIEW: "EMAIL_LOGS_VIEW",
  EMAIL_TYPES_MANAGEMENT: "EMAIL_TYPES_MANAGEMENT",
  SYSTEM_CONFIG: "SYSTEM_CONFIG",

  PHONE_MANAGEMENT: "PHONE_MANAGEMENT",
  ADDRESS_MANAGEMENT: "ADDRESS_MANAGEMENT",
  CREDIT_CARD_MANAGEMENT: "CREDIT_CARD_MANAGEMENT",

  ROLE_MANAGEMENT: "ROLE_MANAGEMENT",
};

//Get the roles from DB
export const ROLES = {
  SUPERADMIN: "SUPERADMIN",
  ADMIN: "ADMIN",
  HELPDESK: "HELPDESK",
  WORKER: "WORKER",
  CUSTOMER: "CUSTOMER",
};

//Verification tokens expire in 24 hours
export const verificationDuration = 24 * 60 * 60 * 1000;
